// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmyhncwloxszvlckinik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhteWhuY3dsb3hzenZsY2tpbmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MTcwOTAsImV4cCI6MjA1NDE5MzA5MH0.c6pKDswIXwyV9hw9yWwWbe76n3B4gUPs6k7A7S_hKcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);